-- 1. List all customers who have made purchases of more than $80.
select * from users;
select * from orders;
select users.user_id, users.user_name, orders.total_amount
from users
left join orders on users.user_id=orders.user_id
where orders.total_amount > 80;
-- 2. Retrieve all orders placed in the last 280 days along with the customer name and email.
select orders.order_id, orders.order_date, orders.user_id, users.user_name, users.email 
from orders
left join users on users.user_id=orders.user_id
where orders.order_date >= curdate() - interval 280 day;
-- 3. Find the average product price for each category.
select category, avg(price) from products group by category;
-- 4. List all customers who have purchased a product from the category Electronics.
select distinct users.user_id, users.user_name 
from users
inner join orders on users.user_id=orders.user_id 
inner join ordersdetails on  orders.order_id=ordersdetails.order_id
inner join products on ordersdetails.product_id=products.product_id
where products.category='Electronics';
-- 5. Find the total number of products sold and the total revenue generated for each product.
select sum(ordersdetails.quantity) as total_products_sold,
sum(orders.total_amount) as total_revenue
from ordersdetails
inner join orders on ordersdetails.order_id=orders.order_id;
-- 6. Update the price of all products in the Books category, increasing it by 10%.
set sql_safe_updates=0;
update products 
set price=price+(price*0.10)
where category='Books';
-- 7. Remove all orders that were placed before 2020
delete from orders 
where order_date<'2020-01-01'; 
-- 8. Write a query to fetch the order details, including customer name, product name, and quantity, for orders placed on 2024-05-01.
select users.user_name, products.product_name, ordersdetails.quantity, orders.order_date
from users
inner join orders on users.user_id=orders.user_id
inner join ordersdetails on  orders.order_id=ordersdetails.order_id
inner join products on ordersdetails.product_id=products.product_id
where orders.order_date='2024-05-01';
-- 9. Fetch all customers and the total number of orders they have placed
select users.user_id, users.user_name, 
count(orders.order_id)  as total_number_of_orders 
from users
left join orders on users.user_id=orders.user_id
group by users.user_id;
-- 10. Retrieve the average rating for all products in the Electronics category
-- rating column is unavailable
-- 11. List all customers who purchased more than 1 units of any product, including the product name and total quantity purchased.
select users.user_id, users.user_name, products.product_name, 
sum(ordersdetails.quantity) as total_quantity_purchased
from users
inner join orders on users.user_id=orders.user_id 
inner join ordersdetails on  orders.order_id=ordersdetails.order_id
inner join products on ordersdetails.product_id=products.product_id
group by users.user_id, products.product_name
having sum(ordersdetails.quantity)>1;
-- 12. Find the total revenue generated by each category along with the category name
select products.category, 
sum(ordersdetails.quantity*products.price) as total_revenue
from products
inner join ordersdetails on ordersdetails.product_id=products.product_id
group by products.category;